version: '3'

services:

        mysql:
          image: mysql
          environment:
        - MYSQL_USER=springuser
        - MYSQL_PASSWORD=ThePassword
        - MYSQL_DATABASE=db_example
        - MYSQL_ROOT_PASSWORD=ThePassword
          ports:
            - "3306:3306"
        expose:
             - "3306"

        users-mysql:
          image: users-mysql
          restart: on-failure
          depends_on:
            - mysql-standalone
          ports:
            - 8080:8080
          environment:
            - DATABASE_HOST=myapp-mysql
            - DATABASE_USER=myapp-user
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=MyAppDb
            - DATABASE_PORT=3306